name: GitHub Actions Demo
run-name: ${{ github.actor }} is testn out GitHub ctions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -ail
      - run : mvn integration-test -Pcoverage
      - run : mvn jacoco:report -Pcoverage
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=nanificateur -Dsonar.projectKey=Nanificateur_jwt -X -Dsonar.analysis.mode= -Dsonar.scm.enabled=false -Dsonar.scm-stats.enabled=false -Dsonar.working.directory=.scannerwork
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time.
        timeout-minutes: 5
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      
