name: GitHub Actions Demo
run-name: ${{ github.actor }} isq testn out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -ail
      - run : mvn integration-test -Pcoverage
      - run : mvn jacoco:report -Pcoverage
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=nanificateur -Dsonar.projectKey=Nanificateur_jwt -X
 
